---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 10.26

platforms:
- name: ubuntu-12.04
  driver_config:
      box: precise64
      box_url: http://files.vagrantup.com/precise64.box
      require_chef_omnibus: true
  run_list:
      - recipe[apt]
      - recipe[repositories]

suites:
- name: default
  run_list: ["recipe[diamond]"]
  attributes:
    diamond:
      graphite_server: ['127.0.0.1']
#      version: "3.3.0+git20130821"
    repositories:
      diamond:
        version: "3.3.0+git20130821"
        uri: "http://15.185.118.80/repositories/diamond/"
        key: "http://15.185.118.80/repositories/diamond/key.pub"
        packages: ["diamond"]
